require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'EcoFast' do
  rn_maps_path = '../node_modules/react-native-maps'
  permissions_path = '../node_modules/react-native-permissions/ios'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # GoogleMaps on iOS
  pod 'react-native-google-maps', path: rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # Permissions
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  target 'EcoFastTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'EcoFast-tvOS' do
  # Pods for EcoFast-tvOS

  target 'EcoFast-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
